stages:
  - build
  - test
  - package

build-job:
  stage: build
  image: maven:3.9.5-eclipse-temurin-17
  script:
    - mvn clean compile

test-job:
  stage: test
  image: maven:3.9.5-eclipse-temurin-17
  script:
    - mvn test

package-job:
  stage: package
  image: maven:3.9.5-eclipse-temurin-17
  script:
    - mvn package
  artifacts:
    paths:
      - target/*.jar

