stages:
  - build
  - test

build-job:
  stage: build
  image: maven:3.9.5-eclipse-temurin-17
  script:
    - mvn clean compile

test-job:
  stage: test
  image: maven:3.9.5-eclipse-temurin-17
  script:
    - mvn test
